### ISSUE TITLE
Computing facies

### ISSUE THREAD

**Issue by Mafalda1996** [randlab/ArchPy#12]
Hello,
I'd like to ask for an help with the following issue
![image](https://github.com/randlab/ArchPy/assets/155142626/07af7150-12bb-4a50-ae25-91506503c9d0)
what could be the meaning of this error? I'm following the tutorial and everything seems done according to the procedure.

**Comment by LudovicSchorpp** [comment]
Hello @Mafalda1996, It seems that the "probability" parameter does not have the required length. This parameter is pass to ArchPy through the dic_facies parameter of a Unit object and is used to control the proportions of each facies for the SIS simulation. 

![image](https://github.com/randlab/ArchPy/assets/51512737/e5497755-2ced-4933-aa2a-d45f04ee055f)

Here it is an example taken from the second notebook (01_basic/2_Hard_data.ipynb). Here a list of two values is passed as "probability" parameter for dic_facies as there is two facies that are simulated inside the unit B (see below). So you should check if that the length of this list and the number of facies match. One last thing, the order in the list is important, as it is the same order in which the facies are passed to the unit (with the ``add_facies()`` function). In this example, Clay will have a proportion of 0.7 and sand 0.3.

![image](https://github.com/randlab/ArchPy/assets/51512737/27b42a46-f399-4878-8019-3c05ff03dc77)

Hope it helps.

**Comment by Mafalda1996** [comment]
Thanks a lot, it helped to fix the issue.
