### ISSUE TITLE
Probability map

### ISSUE THREAD

**Issue by Mafalda1996** [randlab/ArchPy#18]
Hello! I need an help with the probability plot, as you can see in the picture all the values plotted are 1 even if the facies and the unit are computed and plotted properly.
![image](https://github.com/randlab/ArchPy/assets/155142626/6fb908b7-b22a-4d72-9e3d-edfbf9db7a96)
Could you help pls? I'm using SIS interpolation method, thanks a lot.

**Comment by LudovicSchorpp** [comment]
I will need more information:
what command have you tried ?
How many realizations have you done (T1.compute_surf(?)) ?
