### ISSUE TITLE
shannon entropy plots

### ISSUE THREAD

**Issue by Alfaruuki** [randlab/ArchPy#19]
This was the plot I got from plotting the entropy, I dont think it's correct. So what are your recommendations to get the right plot?

![image](https://github.com/randlab/ArchPy/assets/140621039/6826d16e-72fe-4588-ac37-4978d915719f)

Additionally, I plotted the 3d shannon entropy but observed no heterogeneity as well. What could I be  doing wrongly? 

![image](https://github.com/randlab/ArchPy/assets/140621039/71137f77-61ca-46f2-849d-6cb971833cf4)

**Comment by LudovicSchorpp** [comment]
How many realizations have you made? (T1.compute_surf(?)). You need several realizations to make uncertainty estimates. Make sure you have a sufficient number of realizations, here it looks like you've only done one.

**Comment by Alfaruuki** [comment]
Dear Ludovic,

Thank you for your response. Your recommendation solved my problem.
