### ISSUE TITLE
[Suggestion] rename getXX methods to get_XX

### ISSUE THREAD

**Issue by raoulcollenteur** [randlab/ArchPy#5]
I noted some of the "get" methods are inconsistently named, e.g., `T1.getprop` instead of `T1.get_prop` like most of the other methods. It would be nice if all these get-methods are named consistently :)

Cheers,
Raoul

**Comment by LudovicSchorpp** [comment]
Hello Raoul,

Thank you to point this out. Indeed it's a long-standing problem that we have and it was maintained for compatibilities with the codes of Alexis. but now I'm free to update everything, it will be fixed with the next push :)
